global:
  scrape_interval: 15s # for every 15 secondd scare metrics from targets
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'learn-prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          group: 'learn-prometheus-group'